services:
  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile.api
    ports:
      - '3001:3001'

  web:
    build:
      context: ..
      dockerfile: infra/Dockerfile.web
    ports:
      - '8080:80'
    depends_on:
      - api
